<template>
  <footer ref="footer" class="footer">
    TERMENI SI CONDITII: ACESTA ESTE UN SERVICIU DE DIVERTISMENT.  
    PRIN FOLOSIREA LUI DECLARATI CA AVETI 18 ANI IMPLINITI,  
    SI ACCEPTATI TOTI TERMENII SI CONDITIILE NOASTRE.  
    ORICE UTILIZARE NEAUTORIZATA ESTE INTERZISA.  
  </footer>
</template>

